### ISSUE TITLE
pechkin assembly doesn't have strong name

### ISSUE THREAD

**Issue by luismolinaab** [gmanny/Pechkin#82]
Hi, I'm trying to use pechkin in Sharepoint 2013 but when building the solution it says that pechkin is not strong signed and it breaks, any clue?

**Comment by BaobabYeah** [comment]
Hi,

you should be able to download the source code and strongly sign it.

Good luck for your sharepoint development ;)

**Comment by luismolinaab** [comment]
Thanks BaobabYeah
